# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 17:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 6, 7, 17, 27, 41, 932025, tzinfo=utc)),
        ),
    ]
