# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20170607_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 6, 8, 16, 49, 47, 258905, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='danielmiji@gmail.com', max_length=255, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='mji4kef2', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
