# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 08:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_auto_20170608_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 6, 15, 8, 4, 44, 634713, tzinfo=utc)),
        ),
    ]
