# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_auto_20170615_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
