# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_company_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
